import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@utils/authProvider";
import { Navbar } from "@ui-components/Navbar"
import { UserProvider } from "@utils/userProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-brand-light dark:bg-brand-dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}>
        <AuthProvider>
          <UserProvider>
            <Navbar />
            <main className="pt-14">{children}</main> {/* padding so content isn't hidden under navbar */}
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
